### ISSUE TITLE
Can't load save_path

### ISSUE THREAD

**Issue by nanthakumar94** [vinayakkailas/Background_removal_Using_image_segmentation#1]
This is my folder order:
--fcn_8s_checkpoint
--models
--nets
--preprocessing
--recipes
--utils

Traceback (most recent call last):
  File "C:/Users/nanth/PycharmProjects/Background_removal_using_image_segmentation-master/Background_removal_using_image_segmentation-master/segment_image.py", line 59, in <module>
    saver.restore(sess, tf.train.latest_checkpoint(checkpoint_dir='model_fcn8s_final.ckpt'))
  File "C:\Users\nanth\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1713, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None

please tell me, how to load ckpt file in this script and i need only the segmented image only

**Comment by bhavi289** [comment]
First remove the suffix ".data-00000-of-00001" from the checkpoint file.
So model_fcn8s_final.ckpt.data-00000-of-00001 becomes model_fcn8s_final.ckpt

Then change the sess.restore line to this -
<pre>
saver.restore(sess, "fcn_8s_checkpoint/model_fcn8s_final.ckpt")
</pre>
